# Generated by Django 2.1.4 on 2019-10-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets_filter', models.CharField(max_length=100)),
                ('reviews_filter', models.IntegerField(default=0)),
            ],
        ),
    ]
