# Generated by Django 2.1.4 on 2019-10-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='reviews_filter',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='tweets_filter',
        ),
        migrations.AddField(
            model_name='scraper',
            name='business_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
