# Generated by Django 2.1.4 on 2019-10-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0002_auto_20191026_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='radius',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
